blog/urls.py
from .import views
from django.urls import path

urlpatterns = [
    path('<slug:slug>', views.BlogView.as_view(), name='blog_view'),
    path('about/', views.AboutView.as_view(), name='about_view'),
    path('', views.PostList.as_view(), name='home')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('translate/', include('translator.urls'))
    # as an argument of include we put app name
]

translator/urls.py
from .import views
from django.urls import path

urlpatterns = [
    path('', views.translator_view, name='translator_view')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = ((0,'Draft'), (1, 'Publish'))
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200) #article title
    content = models.TextField() #article content
    date_created = models.DateTimeField(auto_now_add=True) #created date
    slug = models.SlugField(max_length=200, unique=True)  # .../slug
    author = models.ForeignKey(to=User, on_delete=models.CASCADE) #article author taken from User table
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return self.title

translator/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from .models import Post
from django.views import generic

# Create your views here.

class BlogView(generic.DetailView):
    model = Post
    template_name = 'blog.html'

class AboutView(generic.TemplateView): #it does not need a model because it's static page, not taking anything from database
    template_name = 'about.html'

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-date_created') #only published posts ordered by date
    template_name = 'index.html'
    

translator/views.py
from django.shortcuts import render
from . import translate

# Create your views here.

def translator_view(request):
    if request.method == 'POST':
        original_text = request.POST['my_textarea']
        output = translate.translate(original_text)
        return render(request, 'translator.html', {'output_text': output, 'original_text':original_text})
    else:
        return render(request, 'translator.html')

templates/about.html
{% extends 'base.html' %}
{% block content %}
        <div class="container">
                <h2>This is the about page!</h2>
                <div>This is the content!</div>
        </div>
        
{% endblock content %}
 

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"> 
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Blog Posts</title>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow mb-5" id="mainNav">
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="navbar-brand p-3" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand p-3" href="{% url 'translator_view' %}">TranslatorApp</a>
                    </li>
                    <li>
                        <a class="navbar-brand p-3" href="{% url 'about_view' %}">About Us</a>
                    </li>
                </ul>
            </div>
        </nav>

{% block content %}
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/blog.html
{% extends 'base.html' %}
{% block content %}
        <h1>
            {{object.title}}
        </h1>
        <p1>
            {{object.content}}
        </p1>
        <p>
            {{object.author}}
        </p>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
        <div class="container">
        {% for post in post_list %}
            <div class="card m-3">
                <div class="card-body">
                    <h2 class="card-title">
                        {{post.title}}
                    </h2>
                    <p class="card-text">
                        {{post.content | slice:"200"}} 
                    </p>
                    <p class="card-text">
                        Author: {{post.author | title}}
                    </p>
                    <a class="btn btn-primary" href="{% url 'blog_view' post.slug %}"> Read more!</a>
                </div>
            </div>
        {% endfor %}
        </div>
{% endblock content %}
       

templates/translator.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form action="{% url 'translator_view' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-5 mt-3 left">
                <textarea class="form-control" rows="3" name="my_textarea">{{original_text}}</textarea>
            </div>
            <div class="col-sm-2 mt-3 text-center">
                <input class="btn btn-primary ml-3 mt-3" type="submit" value="Submit">
            </div>
            <div class="col-sm-5 mt-3 left">
                <textarea class="form-control" rows="3">{{output_text}}</textarea>
            </div>
        </div>
    </form>
</div>
{% endblock content %}